title: Lambda-4S
subtitle: The Smallest Orbital Rocket
nav:
  - title: Lambda-4S Overview
    url: /Lambda-4S/
    name: home
  - title: History
    url: /Lambda-4S/history/
    name: history
  - title: Digitized Data
    url: /Lambda-4S/data/
    name: data
  - title: Simulation
    url: /Lambda-4S/simulation/
    name: simulation

subnav:
    data:
      - title: Overview
        url: /Lambda-4S/data/
        name: data
      - title: First Stage Thrust Curve
        url: /Lambda-4S/data/stage1/
        name: stage1

